name: 🏠 Self-Hosted Metrics

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: [self-hosted, linux, x64]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 📊 Generate metrics on self-hosted runner
        uses: lowlighter/metrics@latest
        with:
          # Core settings
          token: ${{ secrets.GITHUB_TOKEN }}
          user: kzndotsh
          template: classic
          filename: github-metrics.svg
          
          # Base content - show your profile info
          base: header, metadata, repositories
          base_indepth: yes
          repositories: 50
          repositories_forks: no
          
          # Cool plugins for a senior engineer
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_threshold: 1%
          plugin_languages_ignored: html, css, dockerfile, makefile, shell, tex
          
          # Isometric commit calendar - looks amazing!
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Lines of code changed - shows your productivity
          plugin_lines: yes
          plugin_lines_sections: both
          plugin_lines_repositories_limit: 10
          
          # Recent activity - shows you're active
          plugin_activity: yes
          plugin_activity_limit: 20
          plugin_activity_days: 30
          
          # Featured repositories - showcase your best work
          plugin_repositories: yes
          plugin_repositories_featured: kzndotsh/dotfiles, allthingslinux/tux
          plugin_repositories_starred: yes
          plugin_repositories_random: yes
          
          # Achievements - GitHub badges
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 10
          
          # Notable contributions - shows impact
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commits, issues, pull-requests
          
          # Topics you're interested in
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 20
          
          # Recently starred repos - shows learning
          plugin_stars: yes
          plugin_stars_limit: 10
          
          # GitHub Skyline - 3D visualization
          plugin_skyline: yes
          plugin_skyline_year: 2024
          plugin_skyline_frames: 25
          
          # Repositories traffic - page views
          plugin_traffic: yes
          
          # WakaTime - coding time tracking
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_days: 30
          plugin_wakatime_limit: 8
          
          # Configuration
          config_timezone: America/New_York
          config_animations: yes
          config_display: large
          config_padding: 0, 0
          
          # Output settings
          output_action: commit
          output_condition: data-changed
          committer_message: 🏠 Self-hosted metrics update for run #${{ github.run_number }}
          
          # Optimization
          optimize: yes
          verify: yes
          
          # Debug (disable in production)
          debug: no